#!/usr/bin/env python3
"""Set up and optionally start a local production-shaped SAR Workbench.

The command deliberately keeps generated state under ``instance/`` so local
credentials, the SQLite database, uploads, and the shell environment file are
ignored by git. Use ``pixi run setup-local`` for setup only or ``pixi run
local`` to set up and start the pinned Gunicorn server.
"""

from __future__ import annotations

import argparse
import getpass
import os
import secrets
import shlex
import shutil
import subprocess
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from authorization import ensure_local_user  # noqa: E402
from contradiction_engine import run_contradiction_analysis  # noqa: E402
from database import apply_migrations, read_connection, transaction  # noqa: E402
from import_pipeline import (  # noqa: E402
    DuplicateImportError,
    commit_import,
    create_preview,
)
from measurement_engine import summarize_project_measurements  # noqa: E402


DEFAULT_DATABASE = ROOT / "instance" / "local" / "sar.db"
DEFAULT_UPLOAD_DIR = ROOT / "instance" / "local" / "uploads"
DEFAULT_ENV_FILE = ROOT / "instance" / "local.env"
DEFAULT_PROJECT_ID = "local_example_project"
DEFAULT_EMAIL = "scientist@example.org"
DEFAULT_PORT = 5001
DEFAULT_DATASET = "druglike"
FIXTURE_SETS = {
    "druglike": {
        "project_name": "Synthetic drug-like SAR series",
        "primary": ROOT / "examples" / "example_druglike_measurements.csv",
        "followup": ROOT / "examples" / "example_druglike_contradiction_followup.csv",
    },
    "compact": {
        "project_name": "Synthetic SAR full-workflow example",
        "primary": ROOT / "examples" / "example_measurements.csv",
        "followup": ROOT / "examples" / "example_contradiction_followup.csv",
    },
}


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _id(prefix: str) -> str:
    return f"{prefix}_{uuid.uuid4().hex}"


def _ask_yes_no(prompt: str, *, default: bool) -> bool:
    suffix = "[Y/n]" if default else "[y/N]"
    answer = input(f"{prompt} {suffix} ").strip().lower()
    if not answer:
        return default
    if answer in {"y", "yes"}:
        return True
    if answer in {"n", "no"}:
        return False
    print("Please answer yes or no.")
    return _ask_yes_no(prompt, default=default)


def _prompt_email(default: str) -> str:
    while True:
        value = input(f"Local login email [{default}] ").strip().lower() or default
        if "@" in value and " " not in value:
            return value
        print("Enter an email-shaped value, for example scientist@example.org.")


def _prompt_dataset(default: str) -> str:
    print("Example dataset:")
    print("  1) druglike — shared amide/pyridyl series with R-group diversity (recommended)")
    print("  2) compact  — small smoke-test fixture")
    while True:
        value = input(f"Choose dataset [1/{default}] ").strip().lower()
        if not value:
            return default
        if value in {"1", "druglike"}:
            return "druglike"
        if value in {"2", "compact"}:
            return "compact"
        print("Choose 1 for druglike or 2 for compact.")


def _prompt_password(*, non_interactive: bool) -> str:
    if non_interactive:
        value = os.environ.get("SAR_SETUP_PASSWORD", "")
        if not value:
            raise ValueError(
                "Non-interactive setup requires SAR_SETUP_PASSWORD in the environment; "
                "it is used only to create the password hash and is not written."
            )
        return value
    while True:
        value = getpass.getpass("Local login password: ")
        if not value:
            print("The local password cannot be empty.")
            continue
        confirmation = getpass.getpass("Confirm local login password: ")
        if value != confirmation:
            print("Passwords did not match; try again.")
            continue
        return value


def _password_hash(password: str) -> str:
    from werkzeug.security import generate_password_hash

    return generate_password_hash(password)


def _validated_port(value: int) -> int:
    if not 1 <= value <= 65535:
        raise ValueError("Local Gunicorn port must be an integer between 1 and 65535")
    return value


def _write_env_file(path: Path, values: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by /Users/yipyewmun/GitHub/SAR_tool/scripts/setup_local.py",
        "# Local-only credentials and paths. This file must not be committed or shared.",
    ]
    for key, value in values.items():
        lines.append(f"export {key}={shlex.quote(value)}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    path.chmod(0o600)


def _read_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        raise FileNotFoundError(
            f"Local environment file does not exist: {path}. Run 'pixi run setup-local' first."
        )
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if not stripped.startswith("export "):
            raise ValueError(f"Unsupported line in local environment file: {line}")
        assignment = stripped.removeprefix("export ")
        parsed = shlex.split(assignment, comments=False, posix=True)
        if len(parsed) != 1 or "=" not in parsed[0]:
            raise ValueError(f"Invalid environment assignment: {line}")
        key, value = parsed[0].split("=", 1)
        if not key or not key.replace("_", "").isalnum():
            raise ValueError(f"Invalid environment variable name: {key}")
        values[key] = value
    return values


def _ensure_example_project(database_path: str, project_id: str, email: str, project_name: str) -> str:
    user_id = ensure_local_user(database_path, email)
    if not user_id:
        raise RuntimeError(f"Could not create or activate local user {email}")
    now = _now()
    with transaction(database_path) as connection:
        project = connection.execute(
            "SELECT id FROM projects WHERE id = ?",
            (project_id,),
        ).fetchone()
        if project is None:
            connection.execute(
                """
                INSERT INTO projects
                    (id, name, description, status, data_origin, created_at, updated_at)
                VALUES (?, ?, ?, 'active', 'imported', ?, ?)
                """,
                (
                    project_id,
                    project_name,
                    "Created by the local synthetic example setup.",
                    now,
                    now,
                ),
            )
        connection.execute(
            """
            INSERT INTO project_members (project_id, user_id, role, created_at)
            VALUES (?, ?, 'owner', ?)
            ON CONFLICT(project_id, user_id) DO UPDATE SET role = 'owner'
            """,
            (project_id, user_id, now),
        )
    return user_id


def _import_fixture(
    database_path: str,
    upload_dir: str,
    fixture: Path,
    project_id: str,
    user_id: str,
) -> bool:
    try:
        preview = create_preview(
            database_path,
            upload_dir,
            fixture.read_bytes(),
            fixture.name,
            actor_user_id=user_id,
        )
    except DuplicateImportError:
        print(f"Already imported; skipping: {fixture}")
        return False
    if preview["accepted_count"] == 0 or preview["rejected_count"]:
        raise RuntimeError(
            f"Fixture validation failed for {fixture.name}: "
            f"{preview['accepted_count']} accepted, {preview['rejected_count']} rejected"
        )
    result = commit_import(
        database_path,
        preview["import_id"],
        project_id,
        actor_user_id=user_id,
    )
    print(
        f"Imported {fixture.name}: {result['inserted_measurements']} measurements, "
        f"{result['inserted_compounds']} new compounds."
    )
    return True


def _summary_count(database_path: str, project_id: str) -> int:
    with read_connection(database_path) as connection:
        row = connection.execute(
            "SELECT COUNT(*) AS count FROM measurement_summaries ms "
            "JOIN compounds c ON c.id = ms.compound_id WHERE c.project_id = ?",
            (project_id,),
        ).fetchone()
    return int(row["count"])


def _generate_summaries(database_path: str, project_id: str, user_id: str) -> int:
    summaries = summarize_project_measurements(
        database_path,
        project_id,
        actor_user_id=user_id,
    )
    print(f"Generated {len(summaries)} measurement summaries.")
    return len(summaries)


def _start_server(values: dict[str, str]) -> int:
    environment = os.environ.copy()
    environment.update(values)
    gunicorn = Path(sys.executable).with_name("gunicorn")
    if not gunicorn.exists():
        resolved = shutil.which("gunicorn")
        if not resolved:
            raise RuntimeError("Gunicorn was not found; run 'pixi install' first.")
        gunicorn = Path(resolved)
    command = [
        str(gunicorn),
        "--config",
        str(ROOT / "deploy" / "gunicorn.conf.py"),
        "wsgi:app",
    ]
    port = values.get("SAR_GUNICORN_PORT", str(DEFAULT_PORT))
    print(f"Starting SAR Workbench at http://127.0.0.1:{port}")
    print("Press Ctrl-C to stop the local server.")
    return subprocess.call(command, cwd=ROOT, env=environment)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Set up and optionally start a local production-shaped SAR Workbench."
    )
    parser.add_argument("--database", default=str(DEFAULT_DATABASE), help="SQLite database path")
    parser.add_argument("--upload-dir", default=str(DEFAULT_UPLOAD_DIR), help="Upload/quarantine directory")
    parser.add_argument("--env-file", default=str(DEFAULT_ENV_FILE), help="Generated shell environment file")
    parser.add_argument("--email", help="Local login email; interactive setup prompts when omitted")
    parser.add_argument("--project-id", default=DEFAULT_PROJECT_ID, help="Synthetic example project identifier")
    parser.add_argument("--dataset", choices=sorted(FIXTURE_SETS), help="Synthetic fixture profile (default: druglike)")
    parser.add_argument("--port", type=int, help="Loopback Gunicorn port (default: 5001)")
    parser.add_argument(
        "--seed-example",
        action=argparse.BooleanOptionalAction,
        default=None,
        help="Import the primary synthetic CSV (interactive default: yes)",
    )
    parser.add_argument(
        "--seed-contradiction",
        action=argparse.BooleanOptionalAction,
        default=None,
        help="Also import the contradiction follow-up and run contradiction analysis",
    )
    parser.add_argument(
        "--secure-cookies",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="Use Secure cookies; enable only when accessing through HTTPS",
    )
    parser.add_argument("--non-interactive", action="store_true", help="Require SAR_SETUP_PASSWORD and do not prompt")
    parser.add_argument("--start", action="store_true", help="Start Gunicorn after setup")
    parser.add_argument(
        "--start-existing",
        action="store_true",
        help="Load --env-file and start without changing setup or seeding",
    )
    return parser


def _setup(args: argparse.Namespace) -> tuple[dict[str, str], str]:
    if args.dataset and args.dataset not in FIXTURE_SETS:
        raise ValueError(f"Unknown synthetic dataset: {args.dataset}")
    if args.non_interactive:
        email = args.email or DEFAULT_EMAIL
        dataset = args.dataset or DEFAULT_DATASET
        seed_example = bool(args.seed_example)
        seed_contradiction = bool(args.seed_contradiction)
    else:
        email = args.email or _prompt_email(DEFAULT_EMAIL)
        dataset = args.dataset or _prompt_dataset(DEFAULT_DATASET)
        seed_example = args.seed_example if args.seed_example is not None else _ask_yes_no(
            "Import the primary synthetic example data?", default=True
        )
        seed_contradiction = args.seed_contradiction if args.seed_contradiction is not None else (
            _ask_yes_no("Also import the contradiction follow-up?", default=False)
            if seed_example
            else False
        )
    if seed_contradiction:
        seed_example = True
    fixture_set = FIXTURE_SETS[dataset]

    password = _prompt_password(non_interactive=args.non_interactive)
    database_path = str(Path(args.database).expanduser().resolve())
    upload_dir = str(Path(args.upload_dir).expanduser().resolve())
    env_file = Path(args.env_file).expanduser().resolve()
    port = _validated_port(DEFAULT_PORT if args.port is None else args.port)
    values = {
        "SAR_ENV": "production",
        "SAR_DEMO_MODE": "false",
        "SAR_DATABASE_PATH": database_path,
        "SAR_UPLOAD_DIR": upload_dir,
        "SAR_SECRET_KEY": secrets.token_urlsafe(48),
        "SAR_AUTH_MODE": "local",
        "SAR_AUTH_EMAIL": email,
        "SAR_AUTH_PASSWORD_HASH": _password_hash(password),
        "SAR_SECURE_COOKIES": "true" if args.secure_cookies else "false",
        "SAR_LOG_SINK": "stdout",
        "SAR_LOG_LEVEL": "INFO",
        "SAR_LOG_RETENTION_DAYS": "14",
        "SAR_GUNICORN_WORKERS": "1",
        "SAR_GUNICORN_PORT": str(port),
    }
    _write_env_file(env_file, values)
    os.environ.update(values)

    Path(upload_dir).mkdir(parents=True, exist_ok=True)
    schema_version = apply_migrations(database_path)
    user_id = _ensure_example_project(
        database_path,
        args.project_id,
        email,
        fixture_set["project_name"],
    )
    print(f"Dataset: {dataset} — {fixture_set['project_name']}")
    print(f"Local environment written to {env_file} (permissions 0600).")
    print(f"Database ready at {database_path}; schema version {schema_version}.")
    print(f"Project ID: {args.project_id}")

    if seed_example:
        primary_imported = _import_fixture(
            database_path,
            upload_dir,
            fixture_set["primary"],
            args.project_id,
            user_id,
        )
        if primary_imported or _summary_count(database_path, args.project_id) == 0:
            _generate_summaries(database_path, args.project_id, user_id)
    if seed_contradiction:
        followup_imported = _import_fixture(
            database_path,
            upload_dir,
            fixture_set["followup"],
            args.project_id,
            user_id,
        )
        if followup_imported:
            _generate_summaries(database_path, args.project_id, user_id)
            contradiction = run_contradiction_analysis(
                database_path,
                args.project_id,
                value_tolerance=0.5,
                actor_user_id=user_id,
            )
            print(
                "Contradiction analysis: "
                f"{contradiction['counts']['contradictory']} contradictory, "
                f"{contradiction['counts']['unit_conflict']} unit conflicts."
            )

    print("\nNext steps:")
    print(f"  pixi run start-local  # reads {env_file}")
    print(f"  open http://127.0.0.1:{port}")
    return values, str(env_file)


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        if args.start_existing:
            values = _read_env_file(Path(args.env_file).expanduser().resolve())
            port_override = args.port
            if port_override is None and os.environ.get("SAR_GUNICORN_PORT"):
                port_override = int(os.environ["SAR_GUNICORN_PORT"])
            if port_override is not None:
                values["SAR_GUNICORN_PORT"] = str(_validated_port(port_override))
            return _start_server(values)
        values, _ = _setup(args)
        if args.start:
            return _start_server(values)
        return 0
    except (OSError, RuntimeError, ValueError) as exc:
        print(f"Local setup failed: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
